<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function cln_colony_help($path, $arg) {
  switch ($path) {
    case "admin/help#cln_colony":
      return '<p>Evolve humanity into more awesomeness</p>';
      break;
  }
} 

/*
 *	PAGES
 */
function cln_colony_menu () {
	$items['colony'] = array (
		'type' => MENU_NORMAL_ITEM,
		'title' => 'Colony',
		'page callback' => 'cln_colony_pages',
		'page arguments' => array ('colony'),
		'access callback' => 'user_access',
		'access arguments' => array ('access content'),
	);
	return $items;
}

function cln_colony_pages ($page) {
	module_load_include ('php', 'cln_colony', 'pages/'.$page);
	$fn = 'cln_colony_pages_'.$page;
	return $fn();
}

/*
 *	BLOCKS
 */
function cln_colony_block_info () {
	$blocks = array ();
	$blocks['cln_colony_sel_family'] = array (
		'info' => ('Colony: Selector: Family'),
	);
	return $blocks;
}

function cln_colony_block_view ($delta='') {
	$block = array();
	switch ($delta) {
		case 'cln_colony_sel_family':
		module_load_include ('php', 'cln_colony', 'blocks/cln_colony_sel_family');
		$block['content'] = cln_colony_block_sel_family();
		break;
	}
	return $block;
}









