<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function cln_core_help($path, $arg) {
  switch ($path) {
    case "admin/help#cln_core":
      return '<p>Evolve humanity into more awesomeness</p>';
      break;
  }
} 

/*
 *	PAGES
 */
function cln_core_menu () {
	$items['colony'] = array (
		'type' => MENU_NORMAL_ITEM,
		'title' => 'Colony',
		'page callback' => 'cln_core_pages',
		'page arguments' => array ('colony'),
		'access callback' => 'user_access',
		'access arguments' => array ('access content'),
	);
	return $items;
}

function cln_core_pages ($page) {
	module_load_include ('php', 'cln_core', 'pages/'.$page);
	$fn = 'cln_core_pages_'.$page;
	return $fn();
}








