<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function cln_chars_help($path, $arg) {
  switch ($path) {
    case "admin/help#cln_chars":
      return '<p>Manage characters</p>';
      break;
  }
} 

/*
 *	BLOCKS
 */
function cln_chars_block_info () {
	$blocks = array ();
	$blocks['cln_chars_sel_family'] = array (
		'info' => ('Colony - Chars: Family selector'),
	);
	return $blocks;
}

function cln_chars_block_view ($delta='') {
	$block = array();
	switch ($delta) {
		case 'cln_chars_sel_family':
		module_load_include ('php', 'cln_chars', 'blocks/cln_chars_sel_family');
		$block['title'] = 'Select Family';
		$block['content'] = cln_chars_block_sel_family();
		break;
	}
	return $block;
}









