<?php

module_load_include('module', 'nx', 'nx');
nx_mod_initialize(__FILE__);


/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
 /*
function cln_chars_help($path, $arg) {
  switch ($path) {
    case "admin/help#cln_chars":
      return '<p>Manage characters</p>';
      break;
  }
}
*/
